platform :ios, '8.0'

target 'BWPhysicsLab' do
	
	pod 'Masonry', '1.0.2'
	pod 'AFNetworking', '3.1.0'
	pod 'SDWebImage', '4.1.0'
	pod 'MJExtension', '3.0.13'
	pod 'MJRefresh', '3.1.12'
	pod 'YYCategories', '1.0.4'
	pod 'XXNibBridge', '2.3.1'
	pod 'pop', '1.0.10'
    pod 'FLAnimatedImage', '1.0.12'
    
    pod 'UPPaySDK', '3.3.6'  # 银联支付控件
    pod 'UMengUShare/Social/WeChat', '6.4.5'  # 友盟-微信
	
end
