platform :ios, '8.0'

target 'BWPhysicsLab' do
	
	pod 'Masonry', '1.0.2'
	pod 'AFNetworking', '3.1.0'
	pod 'SDWebImage', '4.1.0'
	pod 'MJExtension', '3.0.13'
	pod 'MJRefresh', '3.1.12'
	pod 'YYCategories', '1.0.4'
	pod 'XXNibBridge', '2.3.1'
	pod 'pop', '1.0.10'
	
end
