platform :ios, '9.0'

target 'BWPhysicsLab' do

  pod 'YTKNetwork', '2.0.4'
  pod 'SDWebImage', '4.2.2'
  pod 'Masonry', '1.1.0'
  pod 'MJExtension', '3.0.13'
  pod 'MJRefresh', '3.1.15.1'
  pod 'YYCategories', '1.0.4'
  pod 'SVProgressHUD', '2.2.2'

  target 'BWPhysicsLabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWPhysicsLabUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
