platform :ios, '8.0'

target 'BWPhysicsLabSwift' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '4.4.0'
  pod 'MBProgressHUD', '1.0.0'
  pod 'SnapKit', '3.2.0'
  pod 'SDWebImage', '4.0.0'

  # Pods for BWPhysicsLabSwift

  target 'BWPhysicsLabSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWPhysicsLabSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
