platform :ios, '8.0'

target 'BWOnlineEducationiOS' do
  
	pod 'Masonry', '~> 1.0.1'
	pod 'AFNetworking', '~> 3.1.0'
	pod 'SDWebImage', '~> 3.8.0'
	pod 'MJExtension', '~> 3.0.10'
	pod 'MJRefresh', '~> 3.1.0'

end
